---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: mcp-service-restaurant-gatewayclass
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mcp-service-restaurant-gateway
  namespace: default
spec:
  gatewayClassName: mcp-service-restaurant-gatewayclass
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All

    - name: https
      protocol: HTTPS
      port: 443
      hostname: api-vishalk17.kavish.world
      tls:
        mode: Terminate
        certificateRefs:
          - name: api-vishalk17-kavish-world-tls
      allowedRoutes:
        namespaces:
          from: All

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-service-restaurant-route
  namespace: default
spec:
  parentRefs:
    - name: mcp-service-restaurant-gateway
  hostnames:
    - "api-vishalk17.kavish.world"
  rules:
    # Route for /health endpoint
    - matches:
        - path:
            type: PathPrefix
            value: /health
      backendRefs:
        - name: mcp-service-restaurant
          port: 80
    
    # Route for /mcp endpoint (MCP with SSE transport)
    - matches:
        - path:
            type: PathPrefix
            value: /mcp
      backendRefs:
        - name: mcp-service-restaurant
          port: 80



