apiVersion: v1
kind: Secret
metadata:
  name: oauth-secret
  namespace: default
type: Opaque
stringData:
  # OAuth Server
  OAUTH_SERVER_URL: "https://api-vishalk17.kavish.world"
  JWT_SECRET: "6kBLnW3KYnHpfmhMI7rfeZam0vQ1J1ZKZU3fXMbJdqcDwCBLzyn88D3pffjw6l7+"
  
  # Token Lifetimes
  ACCESS_TOKEN_LIFETIME: "604800"    # 7 days
  REFRESH_TOKEN_LIFETIME: "2592000"  # 30 days
  
  # Default Admin
  DEFAULT_ADMIN_EMAIL: "vishalkapadi17@hotmail.com"
  DEFAULT_ADMIN_NAME: "Vishal Kapadi"
  
  # AWS Cognito Provider
  OAUTH_PROVIDER: "cognito"
  OAUTH_CLIENT_ID: "97l5n6um9nlfvrkqholku3a91"
  OAUTH_CLIENT_SECRET: "2eol1p15oej00h43ljdv085gsikr3rprbusgbstcemi0ug9le0"
  OAUTH_AUTH_URL: "https://ap-south-1fewx16t6r.auth.ap-south-1.amazoncognito.com/oauth2/authorize"
  OAUTH_TOKEN_URL: "https://ap-south-1fewx16t6r.auth.ap-south-1.amazoncognito.com/oauth2/token"
  OAUTH_USERINFO_URL: "https://ap-south-1fewx16t6r.auth.ap-south-1.amazoncognito.com/oauth2/userInfo"
  OAUTH_SCOPES: "openid,email,profile"
  
  # Server
  HOST: "0.0.0.0"
  PORT: "8080"
