apiVersion: v1
data:
  DEFAULT_ADMIN_EMAIL: dmlzaGFsa2FwYWRpMTdAaG90bWFpbC5jb20=
  DEFAULT_ADMIN_NAME: VmlzaGFsIEthcGFkaQ==
  JWT_SECRET: NmtCTG5XM0tZbkhwZm1oTUk3cmZlWmFtMHZRMUoxWktaVTNmWE1iSmRxY0R3Q0JMenluODhEM3BmZmp3Nmw3Kw==
  OAUTH_CLIENT_ID: OTdsNW42dW05bmxmdnJrcWhvbGt1M2E5MQ==
  OAUTH_CLIENT_SECRET: MmVvbDFwMTVvZWowMGg0M2xqZHYwODVnc2lrcjNycHJidXNnYnN0Y2VtaTB1ZzlsZTA=
  OAUTH_SERVER_URL: aHR0cHM6Ly9hcGktdmlzaGFsazE3LmthdmlzaC53b3JsZA==
kind: Secret
metadata:
  creationTimestamp: null
  name: mcp-oauth-secrets
  namespace: default
